# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNovaPoshta():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_novaPoshta(self):
    self.driver.get("https://novaposhta.ua/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Вартість доставки\')]").click()
    self.driver.find_element(By.ID, "DeliveryForm_senderCity").send_keys("Кривий Ріг")
    self.driver.find_element(By.ID, "DeliveryForm_recipientCity").click()
    self.driver.find_element(By.ID, "DeliveryForm_recipientCity").send_keys("Дніпро")
    self.driver.find_element(By.NAME, "DeliveryForm[optionsSeat][1][cost]").click()
    self.driver.find_element(By.NAME, "DeliveryForm[optionsSeat][1][cost]").send_keys("200")
    self.driver.find_element(By.NAME, "DeliveryForm[optionsSeat][1][weight]").click()
    self.driver.find_element(By.NAME, "DeliveryForm[optionsSeat][1][weight]").send_keys("5")
    self.driver.find_element(By.ID, "add-pack").click()
    self.driver.find_element(By.NAME, "DeliveryForm[packing][1][packType]").click()
    self.driver.find_element(By.NAME, "yt0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.XPATH, "//input[@id=\'DeliveryForm_senderCity\']").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Тарифи пакування").click()
    self.vars["win1674"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win1674"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.ID, "add-pack").click()
    self.driver.find_element(By.NAME, "yt0").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header__row .btn-text")
    assert len(elements) == 0
  
