# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRozetka1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_rozetka1(self):
    self.driver.get("https://rozetka.com.ua/ua/")
    self.driver.set_window_size(1051, 798)
    self.driver.find_element(By.XPATH, "//input[@name=\'search\']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search-form__input").send_keys("book")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Знайти\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".simple-slider__item:nth-child(6) .ng-lazyloaded").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button--green").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button_color_white:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button_color_white:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button_color_white:nth-child(3)").click()
    self.driver.find_element(By.LINK_TEXT, "Оформити замовлення").click()
  
