# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRozetka2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_rozetka2(self):
    self.driver.get("https://rozetka.com.ua/ua/")
    self.driver.set_window_size(1054, 800)
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Каталог\')]").click()
    self.driver.find_element(By.LINK_TEXT, "Ноутбуки та комп’ютери").click()
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.find_element(By.CSS_SELECTOR, ".simple-slider__item:nth-child(1) > .portal-brands__item > .ng-lazyloaded").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(2) .portal-grid__cell:nth-child(1) .tile-cats__picture > .ng-star-inserted").click()
    self.driver.find_element(By.CSS_SELECTOR, ".catalog-grid__cell:nth-child(1) .goods-tile__colors-item:nth-child(4) .goods-tile__colors-content:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-button__favorites .wish-button > .ng-star-inserted").click()
    self.driver.close()
  
