# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKiddielandS():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_kiddielandS(self):
    self.driver.get("https://kiddielands.onepage.me/")
    self.driver.set_window_size(1051, 798)
    self.driver.find_element(By.CSS_SELECTOR, ".con-kit-component-button--animation-blink .con-kit-component-button__label").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'root\']/div/div/section/div/div/div/div/div/div/div/div[3]/div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".con-kit-component-grid-list-item:nth-child(1) > .con-kit-component-list-item-accordion svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".con-kit-component-grid-list-item:nth-child(2) > .con-kit-component-list-item-accordion svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".con-kit-component-grid-list-item:nth-child(3) .con-kit-component-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".con-kit-component-grid-list-item:nth-child(4) svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".con-kit-component-label-input--type-fname .con-kit-component-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".con-kit-component-label-input--type-fname .con-kit-component-input").send_keys("Inna")
    self.driver.find_element(By.CSS_SELECTOR, ".con-kit-component-button--animation-blink").click()
  
